[package]
name = "lc00002_add_two_nums"
version = "0.1.0"
edition = "2021"

[dependencies]
basic_data_structures = {path = "../basic_data_structures"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
basic_test_utilities = {path = "../basic_test_utilities"}